### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by yongjianchn** [yongjianchn/ATS-Learn#3]
1

**Comment by yongjianchn** [comment]
2

在 2019年6月14日星期五，Yongjian Xu <notifications@github.com> 写道：

**Comment by yongjianchn** [comment]
@WolfgangBai Fuck off

**Comment by WolfgangBai** [comment]
shut up, bitch.




------------------ 原始邮件 ------------------
发件人: "Yongjian Xu"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 晚上6:14
收件人: "yongjianchn/ATS-Learn"<ATS-Learn@noreply.github.com>;
抄送: "928991159"<928991159@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yongjianchn/ATS-Learn] Test (#3)




@WolfgangBai Fuck off

**Comment by yongjianchn** [comment]
不难看啊，就是引用不方便
> 测试引用

上面应该是引用

**Comment by WolfgangBai** [comment]
please speak english

> shut up, bitch.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Yongjian Xu"<notifications@github.com>; 发送时间: 2019年6月14日(星期五) 晚上6:14 收件人: "yongjianchn/ATS-Learn"<ATS-Learn@noreply.github.com>; 抄送: "928991159"<928991159@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [yongjianchn/ATS-Learn] Test (#3) @WolfgangBai Fuck off — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yongjianchn** [comment]
Why conversation is still not closed.

**Comment by WolfgangBai** [comment]
I have no idea about that.

**Comment by yongjianchn** [comment]
Try again?
